define build_macosx
	@echo "Building openssl for MacOSX $(MACOSX_SDKVERSION) $(1)"
	@echo "Please stand by..."
	mkdir -p $(MACOSX_BASE)-$(1)
	export CC="xcrun -sdk macosx clang -arch $(1)" && (cd $(OPENSSL_SRC) && $(MAKE) clean && ./Configure BSD-generic32 $(CONFIG_VAR) --openssldir=$(MACOSX_BASE)-$(1) && sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c" && $(MAKE) && $(MAKE) install && $(MAKE) clean ) > $(MACOSX_BASE)-$(1)/build-openssl-$(OPENSSL_VERSION).log 2>&1
	touch $(2)

endef
